-- MySQL Script generated by MySQL Workbench
-- Mon May 28 20:24:30 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema boleteria_progra
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `boleteria_progra` ;

-- -----------------------------------------------------
-- Schema boleteria_progra
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `boleteria_progra` DEFAULT CHARACTER SET utf8 ;
USE `boleteria_progra` ;

-- -----------------------------------------------------
-- Table `boleteria_progra`.`rol`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`rol` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`rol` (
  `id_rol` INT NOT NULL,
  `descripcion` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_rol`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`provincia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`provincia` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`provincia` (
  `id_provincia` INT NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id_provincia`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`canton`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`canton` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`canton` (
  `id_canton` INT NOT NULL,
  `descripcion` VARCHAR(50) NULL,
  `id_provincia` INT NULL,
  PRIMARY KEY (`id_canton`),
  INDEX `fk_provincia_canton_idx` (`id_provincia` ASC),
  CONSTRAINT `fk_provincia_canton`
    FOREIGN KEY (`id_provincia`)
    REFERENCES `boleteria_progra`.`provincia` (`id_provincia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`distrito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`distrito` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`distrito` (
  `id_distrito` INT NOT NULL,
  `descripcion` VARCHAR(50) NULL,
  `id_canton` INT NULL,
  PRIMARY KEY (`id_distrito`),
  INDEX `fk_canton_distrito_idx` (`id_canton` ASC),
  CONSTRAINT `fk_canton_distrito`
    FOREIGN KEY (`id_canton`)
    REFERENCES `boleteria_progra`.`canton` (`id_canton`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`direccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`direccion` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`direccion` (
  `id_direccion` INT NOT NULL,
  `id_persona` INT NOT NULL,
  `descripcion` TEXT(500) NULL,
  `id_provincia` INT NULL,
  `id_canton` INT NULL,
  `id_distrito` INT NULL,
  PRIMARY KEY (`id_direccion`, `id_persona`),
  INDEX `fk_direccion_distrito_idx` (`id_distrito` ASC),
  INDEX `fk_direccion_canton_idx` (`id_canton` ASC),
  CONSTRAINT `fk_direccion_distrito`
    FOREIGN KEY (`id_distrito`)
    REFERENCES `boleteria_progra`.`distrito` (`id_distrito`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_direccion_canton`
    FOREIGN KEY (`id_canton`)
    REFERENCES `boleteria_progra`.`canton` (`id_canton`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`seccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`seccion` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`seccion` (
  `id_seccion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(60) NULL,
  PRIMARY KEY (`id_seccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`tipo_escenario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`tipo_escenario` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`tipo_escenario` (
  `id_tipo_escenario` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_escenario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`escenario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`escenario` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`escenario` (
  `id_escenario` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `id_tipo_escenario` INT NULL,
  PRIMARY KEY (`id_escenario`),
  INDEX `fk_tipo_escenario_idx` (`id_tipo_escenario` ASC),
  CONSTRAINT `fk_tipo_escenario`
    FOREIGN KEY (`id_tipo_escenario`)
    REFERENCES `boleteria_progra`.`tipo_escenario` (`id_tipo_escenario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`tipo_identificacion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`tipo_identificacion` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`tipo_identificacion` (
  `id_tipo_identificacion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_identificacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`estado_usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`estado_usuario` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`estado_usuario` (
  `id_estado_usuario` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_estado_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`usuario` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`usuario` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `correo` VARCHAR(45) NULL,
  `password` BINARY(32) NOT NULL,
  `id_tipo_identificacion` INT NULL,
  `id_rol` INT NULL,
  `id_estado_usuario` INT NULL,
  PRIMARY KEY (`id_usuario`),
  INDEX `fk_tipo_identificacion_idx` (`id_tipo_identificacion` ASC),
  INDEX `fk_tipo_rol_idx` (`id_rol` ASC),
  INDEX `fk_estado_usuario_idx` (`id_estado_usuario` ASC),
  CONSTRAINT `fk_tipo_identificacion`
    FOREIGN KEY (`id_tipo_identificacion`)
    REFERENCES `boleteria_progra`.`tipo_identificacion` (`id_tipo_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_rol`
    FOREIGN KEY (`id_rol`)
    REFERENCES `boleteria_progra`.`rol` (`id_rol`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estado_usuario`
    FOREIGN KEY (`id_estado_usuario`)
    REFERENCES `boleteria_progra`.`estado_usuario` (`id_estado_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`usuario_nacional`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`usuario_nacional` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`usuario_nacional` (
  `id_usuario_nacional` INT NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido1` VARCHAR(45) NULL,
  `apellido2` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  PRIMARY KEY (`id_usuario_nacional`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`usuario_juridico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`usuario_juridico` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`usuario_juridico` (
  `id_usuario_juridico` INT NOT NULL,
  `identificacion` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `id_tipo_identificacion` INT NULL,
  `telefono` VARCHAR(45) NULL,
  PRIMARY KEY (`id_usuario_juridico`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`usuario_extranjero`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`usuario_extranjero` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`usuario_extranjero` (
  `id_usuario_extranjero` INT NOT NULL AUTO_INCREMENT,
  `identificacion` VARCHAR(45) NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido1` VARCHAR(45) NULL,
  `apellido2` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `fecha_nacimiento` DATE NULL,
  PRIMARY KEY (`id_usuario_extranjero`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`usuario_dato`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`usuario_dato` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`usuario_dato` (
  `id_usuario_dato` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  INDEX `fk_id_usuario_idx` (`id_usuario` ASC),
  CONSTRAINT `fk_id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `boleteria_progra`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_usuario_nacional`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `boleteria_progra`.`usuario_nacional` (`id_usuario_nacional`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_usuario_juridico`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `boleteria_progra`.`usuario_juridico` (`id_usuario_juridico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_id_usuario_extranjero`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `boleteria_progra`.`usuario_extranjero` (`id_usuario_extranjero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`seccion_escenario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`seccion_escenario` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`seccion_escenario` (
  `id_seccion` INT NOT NULL,
  `id_escenario` INT NOT NULL,
  `id_seccion_escenario` INT NOT NULL AUTO_INCREMENT,
  INDEX `fk_seccion_idx` (`id_seccion` ASC),
  PRIMARY KEY (`id_seccion_escenario`),
  INDEX `fk_escenario_idx` (`id_escenario` ASC),
  CONSTRAINT `fk_seccion`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `boleteria_progra`.`seccion` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escenario`
    FOREIGN KEY (`id_escenario`)
    REFERENCES `boleteria_progra`.`escenario` (`id_escenario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`tipo_seccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`tipo_seccion` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`tipo_seccion` (
  `id_tipo_seccion` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_seccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`tipo_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`tipo_evento` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`tipo_evento` (
  `id_tipo_evento` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_evento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`evento` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`evento` (
  `id_evento` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NOT NULL,
  `datos_generales` TEXT(1000) NOT NULL,
  `id_tipo_evento` INT NOT NULL,
  `maximo_compra` INT NOT NULL,
  PRIMARY KEY (`id_evento`),
  INDEX `fk_tipo_evento_idx` (`id_tipo_evento` ASC),
  CONSTRAINT `fk_tipo_evento`
    FOREIGN KEY (`id_tipo_evento`)
    REFERENCES `boleteria_progra`.`tipo_evento` (`id_tipo_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`horario_evento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`horario_evento` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`horario_evento` (
  `id_horario_evento` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NOT NULL,
  `hora_inicio` TIME(0) NOT NULL,
  `inicio_de_venta` DATE NOT NULL,
  `hora_fin` TIME(0) NOT NULL,
  `id_evento` INT NOT NULL,
  `fin_de_venta` DATE NOT NULL,
  PRIMARY KEY (`id_horario_evento`),
  INDEX `fk_evento_idx` (`id_evento` ASC),
  CONSTRAINT `fk_evento`
    FOREIGN KEY (`id_evento`)
    REFERENCES `boleteria_progra`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`evento_escenario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`evento_escenario` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`evento_escenario` (
  `id_evento_escenario` INT NOT NULL AUTO_INCREMENT,
  `id_evento` INT NULL,
  `id_escenario` INT NULL,
  PRIMARY KEY (`id_evento_escenario`),
  INDEX `fk_evento_idx` (`id_evento` ASC),
  INDEX `fk_escenario_idx` (`id_escenario` ASC),
  CONSTRAINT `fk_evento`
    FOREIGN KEY (`id_evento`)
    REFERENCES `boleteria_progra`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_escenario`
    FOREIGN KEY (`id_escenario`)
    REFERENCES `boleteria_progra`.`escenario` (`id_escenario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`evento_seccion`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`evento_seccion` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`evento_seccion` (
  `id_evento_seccion` INT NOT NULL AUTO_INCREMENT,
  `id_secion` INT NOT NULL,
  `id_evento` INT NOT NULL,
  `id_tipo_seccion` INT NOT NULL,
  PRIMARY KEY (`id_evento_seccion`),
  INDEX `fk_evento_idx` (`id_evento` ASC),
  INDEX `fk_seccion_idx` (`id_secion` ASC),
  INDEX `fk_tipo_seccion_idx` (`id_tipo_seccion` ASC),
  CONSTRAINT `fk_evento`
    FOREIGN KEY (`id_evento`)
    REFERENCES `boleteria_progra`.`evento` (`id_evento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seccion`
    FOREIGN KEY (`id_secion`)
    REFERENCES `boleteria_progra`.`seccion` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_seccion`
    FOREIGN KEY (`id_tipo_seccion`)
    REFERENCES `boleteria_progra`.`tipo_seccion` (`id_tipo_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`seccion_cantidad`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`seccion_cantidad` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`seccion_cantidad` (
  `id_seccion_cantidad` INT NOT NULL AUTO_INCREMENT,
  `id_evento_seccion` INT NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_seccion_cantidad`),
  INDEX `fk_evento_seccion_idx` (`id_evento_seccion` ASC),
  CONSTRAINT `fk_evento_seccion`
    FOREIGN KEY (`id_evento_seccion`)
    REFERENCES `boleteria_progra`.`evento_seccion` (`id_evento_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`seccion_asiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`seccion_asiento` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`seccion_asiento` (
  `id_seccion_asiento` INT NOT NULL AUTO_INCREMENT,
  `id_evento_seccion` INT NOT NULL,
  `asiento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_seccion_asiento`),
  INDEX `fk_evento_seccion_idx` (`id_evento_seccion` ASC),
  CONSTRAINT `fk_evento_seccion`
    FOREIGN KEY (`id_evento_seccion`)
    REFERENCES `boleteria_progra`.`evento_seccion` (`id_evento_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`tipo_pago`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`tipo_pago` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`tipo_pago` (
  `id_tipo_pago` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_pago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`tipo_entrega`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`tipo_entrega` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`tipo_entrega` (
  `id_tipo_entrega` INT NOT NULL AUTO_INCREMENT,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_entrega`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `boleteria_progra`.`encabezado_compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `boleteria_progra`.`encabezado_compra` ;

CREATE TABLE IF NOT EXISTS `boleteria_progra`.`encabezado_compra` (
  `id_encabezado_compra` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  `fecha_compra` DATE NOT NULL,
  `id_evento` INT NOT NULL,
  `id_tipo_entrega` INT NOT NULL,
  `id_tipo_pago` INT NOT NULL,
  PRIMARY KEY (`id_encabezado_compra`),
  INDEX `fk_usuario_idx` (`id_usuario` ASC),
  INDEX `fk_tipo_pago_idx` (`id_tipo_pago` ASC),
  INDEX `fk_tipo_entrega_idx` (`id_tipo_entrega` ASC),
  CONSTRAINT `fk_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `boleteria_progra`.`usuario` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_pago`
    FOREIGN KEY (`id_tipo_pago`)
    REFERENCES `boleteria_progra`.`tipo_pago` (`id_tipo_pago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_tipo_entrega`
    FOREIGN KEY (`id_tipo_entrega`)
    REFERENCES `boleteria_progra`.`tipo_entrega` (`id_tipo_entrega`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
